import { timingSafeEqual } from 'node:crypto';
import { prisma } from '@/lib/db';
import { hashApiKey } from './api-keys';
import { logger } from '@/lib/logger';

// ─── Types ───────────────────────────────────────────────────────────────────
// Locally defined to avoid importing model types from @prisma/client,
// which are not reliably exported in Prisma 7 with the Neon adapter.

interface Merchant {
  id: string;
  clerkUserId: string;
  // NOT NULL as of migration 20260723051942_require_organization_id — every
  // Merchant belongs to exactly one Organization (Phase 1 backfill completed).
  organizationId: string;
  businessName: string;
  webhookUrl: string | null;
  webhookSecret: string | null;
  shopifyShopDomain: string | null;
  shopifyAdminAccessToken: string | null;
  shopifyWebhookSecret: string | null;
  environment: string;
  createdAt: Date;
}

interface ApiKey {
  id: string;
  keyHash: string;
  keyPrefix: string;
  merchantId: string;
  organizationId: string;
  scope: string;
  createdAt: Date;
  revoked: boolean;
}

export type AuthResult =
  | { success: true; merchant: Merchant; apiKey: ApiKey; organizationId: string }
  | { success: false; error: string; status: number };

// ─── API Key Authentication ──────────────────────────────────────────────────

/**
 * Authenticates an inbound API request using the `x-api-key` header.
 *
 * Security measures:
 * - Constant-time comparison via `timingSafeEqual` to prevent timing attacks
 * - Input length validation to reject obviously malformed keys before DB queries
 * - Revocation check against the database
 * - Errors are sanitized — no internal details leak to the caller
 */
export async function authenticateApiKey(request: Request): Promise<AuthResult> {
  const apiKeyHeader = request.headers.get('x-api-key');

  if (!apiKeyHeader) {
    return { success: false, error: 'Missing x-api-key header', status: 401 };
  }

  // Reject obviously malformed keys before touching the database.
  // CUID keys generated by Prisma are typically 25 chars, but we allow a generous range.
  if (apiKeyHeader.length < 10 || apiKeyHeader.length > 128) {
    return { success: false, error: 'Invalid API key format', status: 401 };
  }

  try {
    const providedHash = hashApiKey(apiKeyHeader);

    const apiKeyRecord = await prisma.apiKey.findUnique({
      where: { keyHash: providedHash },
      include: { merchant: true },
    });

    if (!apiKeyRecord) {
      return { success: false, error: 'Invalid API key', status: 401 };
    }

    if (apiKeyRecord.revoked) {
      return { success: false, error: 'API key has been revoked', status: 401 };
    }

    // Constant-time comparison on the hash for defense-in-depth against timing attacks.
    const providedBuffer = Buffer.from(providedHash, 'utf-8');
    const storedBuffer = Buffer.from(apiKeyRecord.keyHash, 'utf-8');

    if (providedBuffer.length !== storedBuffer.length || !timingSafeEqual(providedBuffer, storedBuffer)) {
      return { success: false, error: 'Invalid API key', status: 401 };
    }

    // organizationId is NOT NULL as of migration 20260723051942 — guaranteed present.
    return {
      success: true,
      merchant: apiKeyRecord.merchant,
      apiKey: apiKeyRecord,
      organizationId: apiKeyRecord.organizationId,
    };
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    logger.error('API Key authentication error:', message);
    // Never leak internal error details to the client
    return { success: false, error: 'Authentication service unavailable', status: 500 };
  }
}
