import { timingSafeEqual } from 'node:crypto';
import { prisma } from '@/lib/db';
import type { Merchant, ApiKey } from '@prisma/client';

// ─── Types ───────────────────────────────────────────────────────────────────

export type AuthResult =
  | { success: true; merchant: Merchant; apiKey: ApiKey }
  | { success: false; error: string; status: number };

// ─── API Key Authentication ──────────────────────────────────────────────────

/**
 * Authenticates an inbound API request using the `x-api-key` header.
 *
 * Security measures:
 * - Constant-time comparison via `timingSafeEqual` to prevent timing attacks
 * - Input length validation to reject obviously malformed keys before DB queries
 * - Revocation check against the database
 * - Errors are sanitized — no internal details leak to the caller
 */
export async function authenticateApiKey(request: Request): Promise<AuthResult> {
  const apiKeyHeader = request.headers.get('x-api-key');

  if (!apiKeyHeader) {
    return { success: false, error: 'Missing x-api-key header', status: 401 };
  }

  // Reject obviously malformed keys before touching the database.
  // CUID keys generated by Prisma are typically 25 chars, but we allow a generous range.
  if (apiKeyHeader.length < 10 || apiKeyHeader.length > 128) {
    return { success: false, error: 'Invalid API key format', status: 401 };
  }

  try {
    const apiKeyRecord = await prisma.apiKey.findUnique({
      where: { key: apiKeyHeader },
      include: { merchant: true },
    });

    if (!apiKeyRecord) {
      return { success: false, error: 'Invalid API key', status: 401 };
    }

    if (apiKeyRecord.revoked) {
      return { success: false, error: 'API key has been revoked', status: 401 };
    }

    // Constant-time comparison to defend against timing attacks.
    // Even though findUnique does an exact DB match, this layer protects against
    // subtle timing differences in DB query execution or future architecture changes.
    const providedBuffer = Buffer.from(apiKeyHeader, 'utf-8');
    const storedBuffer = Buffer.from(apiKeyRecord.key, 'utf-8');

    if (providedBuffer.length !== storedBuffer.length || !timingSafeEqual(providedBuffer, storedBuffer)) {
      return { success: false, error: 'Invalid API key', status: 401 };
    }

    return { success: true, merchant: apiKeyRecord.merchant, apiKey: apiKeyRecord };
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    console.error('API Key authentication error:', message);
    // Never leak internal error details to the client
    return { success: false, error: 'Authentication service unavailable', status: 500 };
  }
}
